/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package nrkdictGUI;

import javax.swing.JFrame;
import javax.swing.JOptionPane;
import nrkdict.*;

/**
 *
 * @author narko
 */
public class AddWordJDialog extends javax.swing.JDialog {

    /**
     * Creates new form AddWordJDialog
     */
    public AddWordJDialog(java.awt.Frame parent, boolean modal, String term) {
        super(parent, modal);
        initComponents();
        termjTextField.setText(term);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        namejLabel = new javax.swing.JLabel();
        termjTextField = new javax.swing.JTextField();
        canceljButton = new javax.swing.JButton();
        savejButton = new javax.swing.JButton();
        namejLabel1 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        definitionjTextArea = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        namejLabel.setText("Insert the new term:");

        canceljButton.setText("Cancel");
        canceljButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                canceljButtonMouseClicked(evt);
            }
        });

        savejButton.setText("Save");
        savejButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                savejButtonMouseClicked(evt);
            }
        });

        namejLabel1.setText("Definition:");

        definitionjTextArea.setColumns(20);
        definitionjTextArea.setRows(5);
        jScrollPane3.setViewportView(definitionjTextArea);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 489, Short.MAX_VALUE)
                    .addComponent(termjTextField)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(canceljButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(savejButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(namejLabel)
                            .addComponent(namejLabel1))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(namejLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(termjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(namejLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(canceljButton)
                    .addComponent(savejButton))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void canceljButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_canceljButtonMouseClicked
        dispose();
    }//GEN-LAST:event_canceljButtonMouseClicked

    private void savejButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_savejButtonMouseClicked
        if (!termjTextField.getText().equals("") && !definitionjTextArea.getText().equals("")){
            int ret = NrkDict.guiController.createTerm(termjTextField.getText(), definitionjTextArea.getText());
            if (ret < 0) {
                JOptionPane jp = new JOptionPane();
                JFrame jf = new JFrame();
                JOptionPane.showMessageDialog(jf,
                    "Term already exist",
                    "Inane warning",
                    JOptionPane.WARNING_MESSAGE);
            }
            else 
                dispose();
        }
    }//GEN-LAST:event_savejButtonMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton canceljButton;
    private javax.swing.JTextArea definitionjTextArea;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel namejLabel;
    private javax.swing.JLabel namejLabel1;
    private javax.swing.JButton savejButton;
    private javax.swing.JTextField termjTextField;
    // End of variables declaration//GEN-END:variables
}
